Traceback (most recent call last):
  File "/Volumes/Seagate/monotrac/nextflow/bin/depth_plots.py", line 32, in <module>
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/PIL/Image.py", line 2456, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Seagate/monotrac/nextflow/work/28/12f3222b53a4e2664258e46d89daf9/Depth_plots/barcode3_consensus_depth.png'
